[project]
name = "talentscout-assignment"
version = "0.1.0"
description = "Assignment Project for Internship"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "openai",
    "streamlit",
]
